controller_list:
#  - name: arm_1/arm_controller
  - name: arm_moveit/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - z_joint
      - x_joint
      - y_joint
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5

#  - name: multi_dof_joint_trajectory_action
#    type: MultiDofFollowJointTrajectory
#    default: true
#    joints:
#      - virtual_joint

#  - name: arm_1/gripper_controller
#    action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    default: true
#    joints:
#      - gripper_finger_joint_l
#      - gripper_finger_joint_r