# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_joint_1:
    has_velocity_limits: true
    max_velocity: 1 # 1.57079632679
    has_acceleration_limits: false
    max_acceleration: 0
  arm_joint_2:
    has_velocity_limits: true
    max_velocity: 1 # 1.57079632679
    has_acceleration_limits: false
    max_acceleration: 0
  arm_joint_3:
    has_velocity_limits: true
    max_velocity: 1 # 1.57079632679
    has_acceleration_limits: false
    max_acceleration: 0
  arm_joint_4:
    has_velocity_limits: true
    max_velocity: 1 # 1.57079632679
    has_acceleration_limits: false
    max_acceleration: 0
  arm_joint_5:
    has_velocity_limits: true
    max_velocity: 1 # 1.57079632679
    has_acceleration_limits: false
    max_acceleration: 0
  x_joint:
#    has_position_limits: true
#    max_position: 7
#    min_position: -7
    has_velocity_limits: true
    max_velocity: 0.8 # 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  y_joint:
#    has_position_limits: true
#    max_position: 9
#    min_position: -9
    has_velocity_limits: true
    max_velocity: 0.8 # 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  z_joint:
    has_velocity_limits: true
    max_velocity: 0.8 # 0.3
    has_acceleration_limits: false
    max_acceleration: 0