robot:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin

  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005 # not applicable for trac ik
  kinematics_solver_timeout: 0.05
#  kinematics_solver_attempts: 3 # not applicable for trac ik, it will auto-restart
  # solve_type: Distance
  position_only_ik: True
arm:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin

  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
#  kinematics_solver_attempts: 3
#  solve_type: Distance
  position_only_ik: True

base:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin

  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
#  kinematics_solver_attempts: 3
#  solve_type: Distance
  position_only_ik: True